### ISSUE TITLE
Starting with a supervisor

### ISSUE THREAD

**Issue by ramontayag** [RooSoft/lnd_client#10]
I was wondering how to allow creation of multiple genservers when an app would talk to multiple. Patterning it after what I've seen elsewhere (to allow a supervisor to watch it), something like this could work:

```ex
defmodule Webapp.Application do

  def start(_type, _args) do
    children = [
      # ...
      {
        LndClient,
        %{
          node_uri: System.get_env("NODE"),
          cert_path: System.get_env("CERT"),
          macaroon_path: System.get_env("MACAROON")
        },
      },
    ]

    opts = [strategy: :one_for_one, name: Webapp.Supervisor]
    Supervisor.start_link(children, opts)
  end

end
```

This means changing `LndClient.start_link` to something like this (sorry for the code, I just wanted to get it to work):

```ex
  def start_link(%{node_uri: node_uri, cert_path: cert_path, macaroon_path: macaroon_path}) do
    state = %{
      node_uri: node_uri,
      cert_path: cert_path,
      macaroon_path: macaroon_path
    } |> init_subscriptions

    result = GenServer.start_link(__MODULE__, state, name: __MODULE__)

    GenServer.call(__MODULE__, :connect, :infinity)

    result
  end
```

My thinking behind this is once it starts, it makes a connection to LND. This way, if it shuts down and restarted by the supervisor, the connection will get re-established.

There are other things to think about, such as updating convenience methods to easily work with named processes (which is what is recommended when handling mutliple processes), but how does the general direction of this look?

**Comment by RooSoft** [comment]
Makes a lot of sense...

Should have been made this way from the start.

A PR along those lines will have a high probability to be merged.

**Comment by RooSoft** [comment]
To make sure the connection holds, the process should probably kill itself upon deconnection, so that the supervisor restarts a new one in an attempt to make a new connection.

One question I have about the automatic restarting though... what if for some reason LND closes the connection and refuses new connections while the supervisor relentlessly starts new processes, and thus new connections? Could happen during an upgrade, for instance...

That's been a question since the early days of this lib. One solution I see would be to kill the process if LND disconnects, but add a sane delay before doing so.

**Comment by ramontayag** [comment]
Interesting. I didn't consider that. I would like this library to be noisy if that's the case (but not raise exceptions that flood a monitoring tool).

What is a good timeout? It should be configurable, and have a good default. 30 seconds?

**Comment by RooSoft** [comment]
🤷‍♂️

**Comment by RooSoft** [comment]
Are we good with this issue?

**Comment by ramontayag** [comment]
Yes, thanks! I'll make new ones for the other stuff you mentioned.
